# Generated by Django 3.1 on 2020-08-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('target', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageToCompare', models.ImageField(upload_to='images')),
                ('objetivo', models.CharField(max_length=150)),
                ('imageTarget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug.uploadtarget')),
            ],
        ),
    ]
